name: app-ext-val
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - blas=1.0
  - bleach=4.1.0
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - charset-normalizer=2.0.4
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.6.2
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - json5=0.9.6
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib-base=3.8.4
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mysql=5.7.24
  - ncurses=6.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycparser=2.21
  - pyqt=5.15.10
  - python=3.11.9
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - qt-main=5.15.2
  - readline=8.2
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.5
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - anyio==4.2.0
    - argon2-cffi-bindings==21.2.0
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.11.0
    - beautifulsoup4==4.12.3
    - bottleneck==1.3.7
    - brotli==1.0.9
    - certifi==2024.7.4
    - cffi==1.16.0
    - comm==0.2.1
    - contourpy==1.2.0
    - debugpy==1.6.7
    - et-xmlfile==1.1.0
    - fastjsonschema==2.16.2
    - fonttools==4.51.0
    - idna==3.7
    - ipykernel==6.28.0
    - ipython==8.25.0
    - ipywidgets==8.1.2
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.14.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.11
    - jupyterlab-server==2.25.1
    - jupyterlab-widgets==3.0.10
    - kiwisolver==1.4.4
    - markupsafe==2.1.3
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - notebook==7.0.8
    - notebook-shim==0.2.3
    - numexpr==2.8.7
    - numpy==1.26.4
    - openpyxl==3.1.2
    - overrides==7.4.0
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - pip==24.0
    - platformdirs==3.10.0
    - ply==3.11
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.43
    - psutil==5.9.0
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pyqt5==5.15.10
    - pyqt5-sip==12.13.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.30.2
    - requests==2.32.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - scikit-learn==1.4.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - send2trash==1.8.2
    - setuptools==69.5.1
    - sip==6.7.12
    - sniffio==1.3.0
    - soupsieve==2.5
    - statsmodels==0.14.2
    - terminado==0.17.1
    - threadpoolctl==3.5.0
    - tinycss2==1.2.1
    - tornado==6.4.1
    - tqdm==4.66.4
    - traitlets==5.14.3
    - typing-extensions==4.11.0
    - unicodedata2==15.1.0
    - urllib3==2.2.2
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - wheel==0.43.0
    - widgetsnbextension==4.0.10